### ISSUE TITLE
Support turn off for Samsung The Frame

### ISSUE THREAD

**Issue by balmli** [balmli/com.samsung.smart#10]
KEY_POWER does not turn off "The Frame", but switches to art mode.

5 sec press is completely off.

**Comment by Vincent75b** [comment]
Yes please!

**Comment by balmli** [comment]
I have not found a solution yet, I'm afraid.

**Comment by Vincent75b** [comment]
I am not a programmer, but let me know if I can help.

**Comment by balmli** [comment]
Seems to be possible, according to this info:
https://www.c4forums.com/topic/24653-samsung-frame-tv-ip-driver/

**Comment by balmli** [comment]
Added v. 1.4.1, as alpha-version, that might fix this issue.  Please send a message to me on https://community.athom.com/ to be an alpha tester.

**Comment by balmli** [comment]
Check v. 1.5.0 in app store now (beta).

**Comment by Vincent75b** [comment]
Hello Bjornar,

150 works ok. I can now turn off the tv from a flow, so I am happy!

When controlling from devices, the on/off button Goes out off sync
sometimes ( so the tv is off, but I cannot turn it on because app thinks it
is already Turned on... and vice versa. But this only happens when I don’t
respect the ‘two minutes rule’ (for some reason the button in devices does
not update to the current on/state anymore)

Thanks again and let me know if I can do more testing...

Regards,
Vincent

**Comment by balmli** [comment]
Thanks Vincent,

Yes, I guess I have to look at the sync-algorithm again..  

The TV is polled every second when powering on / off.. and there might be some bad effect here that I have not seen yet.

As I have said to different people: The request to the TV that checks if the TV is on / off cannot always be trusted.  The API works for a while, after the TV is turned off.  Then it goes off, and some times it even goes back on..  and after more time if finally goes to sleep...

**Comment by balmli** [comment]
I close this issue, but will look at the power on / off algorithm...

**Comment by balmli** [comment]
See #15 for power on / off
