### ISSUE TITLE
Better algorithm to check if the TV is on/off during power on/off

### ISSUE THREAD

**Issue by balmli** [balmli/com.samsung.smart#15]

**Comment by afTrolle** [comment]
Hi, Awesome work with the Samsung integration! 

I just got a Samsung Frame TV,
Noticed that you had some problems with Tracking if Device is on or off with Frame Tvs.
Due to it being turned off and therefor not responding to network calls.
Think it would be nice improvement would be to assume it's offline if you are get a timeouted when checking if it's on, assuming you are using TCP.

I noticed in the SAMSUNG LEGACY PLATFORM that they support Device Discovery with SSDP protocol (Simple Service Discovery Protocol) [Samsung Link here](https://developer.samsung.com/smarttv/develop/legacy-platform-library/art00030/index.html#contents)
`MSearch ST: urn:samsung.com:service:MultiScreenService:1`

I'm not sure if this is supported on newer device though, but if it is then you could use the [node-ssdp](https://www.npmjs.com/package/node-ssdp) to fetch the samsung tvs and check if it's got a new ip.

**Comment by balmli** [comment]
Hi, thanks!

It actually does a HTTP GET, with a 2000 ms timeout.  But the problem is that the network interface is "on" some times even if the TV is actually off....  The network interface wakes up, and the HTTP GET polling reports that the TV is on. so it's hard for the app to know what the state is.  It's not possible, as far as I know, to see the state 100 % correctly by doing a HTTP GET..  

Now in the latest version I've added support for the SmartThings API.  I've seen that polling the SmartThings API is a bit better when it comes to checking if the TV is on / off.  So you can try that.   It also has better support for selecting the input source (HDMI1, HDMI2, etc..).

And you can also use a wall plug to check the power usage.. If it's above 10 Watts.. the TV is on.

The Homey SDKs support different discovery methods, also SSDP.  I guess that would be better than the current "IP scan" method..  but that would require some testing and volunteers for testing.   I just have one Samsung TV you see :-)

**Comment by mhoogenbosch** [comment]
Is it possible to do it manually. For example to create a actioncard with 'set TV to OFF' and then don't send any commands to the TV but just set the TV to OFF in the gui of Homey? I do a powermeasure for my TV and am pretty sure when it's consuming less than 40 watt it is turned off...  this doens't always get reflected in the GUI.

**Comment by mhoogenbosch** [comment]
@balmli this issue can be closed too

**Comment by mhoogenbosch** [comment]
I can confirm, I've got the powerstate command too:

{
  "device": {
    "FrameTVSupport": "false",
    "GamePadSupport": "true",
    "ImeSyncedSupport": "true",
    "Language": "nl_NL",
    "OS": "Tizen",
    "PowerState": "on",
    "TokenAuthSupport": "true",
    "VoiceSupport": "true",
    "WallScreenRatio": "0",
    "WallService": "false",
    "countryCode": "NL",
    "description": "Samsung DTV RCR",
    "developerIP": "0.0.0.0",
    "developerMode": "0",
    "duid": "uuid:6962bd7e8ee",
    "firmwareVersion": "Unknown",
    "id": "uuid:6962b9ec-3d7e8ee",
    "ip": "192.168.21.17",
    "model": "20_NIKEM_8K",
    "modelName": "QE75Q800TALXXN",
    "name": "[TV] Samsung Q800 Series (75)",
    "networkType": "wired",
    "resolution": "7680x4320",
    "smartHubAgreement": "true",
    "type": "Samsung SmartTV",
    "udn": "uuid:6962b9ec-22768ee",
    "wifiMac": "98:06:3c:a1:54:b4"
  },
  "id": "uuid:6962b9ec-2276-408d",
  "isSupport": "{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"false\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n",
  "name": "[TV] Samsung Q800 Series (75)",
  "remote": "1.0",
  "type": "Samsung SmartTV",
  "uri": "http://192.168.21.17:8001/api/v2/",
  "version": "2.0.25"
}
